# Development overrides for docker-compose
version: '3.8'

services:
  # PostgreSQL with development settings
  postgres:
    environment:
      POSTGRES_DB: nixbit_dev
      POSTGRES_USER: nixbit_dev
      POSTGRES_PASSWORD: dev_password
    ports:
      - "5433:5432"

  # Redis with development settings
  redis:
    ports:
      - "6380:6379"
    command: redis-server --appendonly yes

  # Backend with development environment
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      NODE_ENV: development
      DATABASE_URL: postgresql://nixbit_dev:dev_password@postgres:5432/nixbit_dev
      REDIS_URL: redis://redis:6379
      JWT_SECRET: dev_jwt_secret_key_change_in_production
      PORT: 3001
      CORS_ORIGIN: http://localhost:3000,http://localhost:3002
    volumes:
      - ./backend/src:/app/src:ro
      - ./backend/logs:/app/logs
      - ./shared:/app/shared:ro
    command: npm run dev

  # Frontend with development hot reload
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    environment:
      REACT_APP_API_URL: http://localhost:3001
      REACT_APP_ENVIRONMENT: development
    volumes:
      - ./frontend/src:/app/src:ro
      - ./shared:/app/shared:ro
    command: ["npm", "run", "dev", "--", "--host", "0.0.0.0"]
    ports:
      - "3000:5173"

  # Admin frontend with development hot reload
  admin-frontend:
    build:
      context: ./admin-frontend
      dockerfile: Dockerfile
    environment:
      REACT_APP_API_URL: http://localhost:3001
      REACT_APP_ENVIRONMENT: development
    volumes:
      - ./admin-frontend/src:/app/src:ro
      - ./shared:/app/shared:ro
    command: ["npm", "run", "dev", "--", "--host", "0.0.0.0"]
    ports:
      - "3002:5173"