version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: nixbit-postgres-dev
    restart: unless-stopped
    environment:
      POSTGRES_DB: nixbit_dev
      POSTGRES_USER: nixbit_dev
      POSTGRES_PASSWORD: dev_password
    ports:
      - "5433:5432"
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
    networks:
      - nixbit-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U nixbit_dev"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Redis Cache
  redis:
    image: redis:7-alpine
    container_name: nixbit-redis-dev
    restart: unless-stopped
    ports:
      - "6380:6379"
    volumes:
      - redis_dev_data:/data
    networks:
      - nixbit-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    command: redis-server --appendonly yes

  # Backend API (Development)
  backend:
    build:
      context: ./backend
    container_name: nixbit-backend-dev
    restart: unless-stopped
    environment:
      NODE_ENV: development
      DATABASE_URL: postgresql://nixbit_dev:dev_password@postgres:5432/nixbit_dev
      REDIS_URL: redis://redis:6379
      JWT_SECRET: dev_jwt_secret_key_change_in_production
      PORT: 3001
      CORS_ORIGIN: http://localhost:3000,http://localhost:3002,http://localhost:5173
    ports:
      - "3001:3001"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - nixbit-network
    volumes:
      - ./backend/src:/app/src:ro
      - ./backend/logs:/app/logs
      - ./shared:/app/shared:ro
    command: ["npm", "run", "dev"]

  # Frontend Dashboard (Development)
  frontend:
    build:
      context: ./frontend
    container_name: nixbit-frontend-dev
    restart: unless-stopped
    environment:
      REACT_APP_API_URL: http://localhost:3001
      REACT_APP_ENVIRONMENT: development
    ports:
      - "3000:5173"
    depends_on:
      - backend
    networks:
      - nixbit-network
    volumes:
      - ./frontend/src:/app/src:ro
      - ./shared:/app/shared:ro
    command: ["npm", "run", "dev", "--", "--host", "0.0.0.0"]

  # Admin Dashboard (Development)
  admin-frontend:
    build:
      context: ./admin-frontend
    container_name: nixbit-admin-dev
    restart: unless-stopped
    environment:
      REACT_APP_API_URL: http://localhost:3001
      REACT_APP_ENVIRONMENT: development
    ports:
      - "3002:5173"
    depends_on:
      - backend
    networks:
      - nixbit-network
    volumes:
      - ./admin-frontend/src:/app/src:ro
      - ./shared:/app/shared:ro
    command: ["npm", "run", "dev", "--", "--host", "0.0.0.0"]

networks:
  nixbit-network:
    driver: bridge

volumes:
  postgres_dev_data:
    driver: local
  redis_dev_data:
    driver: local