[build]
  publish = "marketing/dist"
  command = "npm run build:shared && npm run build:marketing"

[build.environment]
  NODE_VERSION = "18"
  VITE_API_URL = "/.netlify/functions"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# Redirect /app/* to the main application (if you want to keep the old app accessible)
[[redirects]]
  from = "/app/*"
  to = "/app/index.html"
  status = 200

# Marketing site SPA routing - catch all other routes
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  command = "npm run dev:marketing"
  targetPort = 5174
  port = 8888
  publish = "marketing/dist"
  autoLaunch = true